### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [sinelaw/xml-to-json#9]
```
xml-to-json               > /tmp/stack-0f056ee49d19dd3b/xml-to-json-2.0.1/src/Text/XML/JSON/XmlToJson.hs:114:41: error:
xml-to-json               >     • Couldn't match expected type ‘Aeson.Key’
xml-to-json               >                   with actual type ‘T.Text’
xml-to-json               >     • In the expression: packJSValueName a
xml-to-json               >       In the expression: (packJSValueName a, b)
xml-to-json               >       In the first argument of ‘Aeson.object’, namely
xml-to-json               >         ‘[(packJSValueName a, b)]’
xml-to-json               >     |
xml-to-json               > 114 | wrapRoot (Just (a, b)) = Aeson.object [(packJSValueName a, b)]
xml-to-json               >     |                                         ^^^^^^^^^^^^^^^^^
xml-to-json               > 
xml-to-json               > /tmp/stack-0f056ee49d19dd3b/xml-to-json-2.0.1/src/Text/XML/JSON/XmlToJson.hs:122:20: error:
xml-to-json               >     • Couldn't match type: HashMap.HashMap T.Text Aeson.Value
xml-to-json               >                      with: Data.Aeson.KeyMap.KeyMap Aeson.Value
xml-to-json               >       Expected: [(JSValueName, Aeson.Value)] -> Aeson.Object
xml-to-json               >         Actual: [(JSValueName, Aeson.Value)]
xml-to-json               >                 -> HashMap.HashMap T.Text Aeson.Value
xml-to-json               >     • In the second argument of ‘(.)’, namely
xml-to-json               >         ‘HashMap.fromList . (map . first) packJSValueName’
xml-to-json               >       In the first argument of ‘($)’, namely
xml-to-json               >         ‘Aeson.Object . HashMap.fromList . (map . first) packJSValueName’
xml-to-json               >       In the expression:
xml-to-json               >         Aeson.Object . HashMap.fromList . (map . first) packJSValueName
xml-to-json               >           $ M.toList m
xml-to-json               >     |
xml-to-json               > 122 |     Aeson.Object . HashMap.fromList . (map . first) packJSValueName $ M.toList m
xml-to-json               >     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by DavidEichmann** [comment]
PR #10 should resolve this issue
